# Site Settings
title: Hoja de Vida/CV Roxana Jofre.
# url: 'http://webjeda.com'
# url: 'http://127.0.0.1:4000'
# url: 'https://bitacoraroot.github.io'
url: "https://resumen.roxanajofre.ga"
# baseurl: '/online-cv' #change it according to your repository name
# baseurl: '/rjofrecv' #change it according to your repository name
#baseurl: '' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2  #Dusty Teal
#style: styles-3  #Light Forest Green
style: styles-4  #Dark Mavue
#style: styles-5  #Dull Orange
#style: styles-6 #Dark Gray Blue


#Profile information
# name: Rosa Roxana Jofré Heredia
name: Roxana Jofre
tagline: MBA. Admin. de Empresas
registro: CADEC N° JRH-318  # Include by TeroRERO
pic: rjofre.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '¡Hola! Mi nombre es Roxana Jofre Heredia. Soy MBA. Administradora de Empresas con 15 años de experiencia.
Vivo en la ciudad de La Paz - Bolivia, pero trabajé
y sigo trabajando con personas de todo el mundo.<br>Por favor tómese su
tiempo, revise mi curriculum, mis habilidades, algo de mi
trabajo, mi experiencia y cuando quiera, envíeme un mensaje.<br><br>
Descargue <a href="https://www.roxanajofre.ga/resumen.pdf" target="_blank">mi resumen/CV aquí</a>.'

#sidebar links
email: info@roxanajofre.ga
phone: 591 2 2418455
mobile: 591 680 82160
website: www.roxanajofre.ga #do not add http://
linkedin: roxanajofre
github: roxanajofre
whatsapp: 59168082160     #New update by TeroRERO
facebook: roxanajofre   #New update by TeroRERO
twitter: '@roxanajofre'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
